apps/job/urls.py
from django.urls import path, include
from .api import api_search
from .views import add_job, job_detail, apply_for_job, search, edit_job, success

urlpatterns = [
    path('success/', success, name='success'),
    path('api/search/', api_search, name='api_search'),
    path('search/', search, name='search'),
    path('add/', add_job, name='add_job'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/edit/', edit_job, name='edit_job'),
    path('<int:job_id>/apply_for_job/', apply_for_job, name='apply_for_job'),
]

dailyjobsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from apps.core.views import frontpage, signup
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name = 'core/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.userprofile.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('jobs/', include('apps.job.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/job/models.py
from django.contrib.auth.models import User
from django.db import models
#from PIL import Image


class Job(models.Model):

    title = models.CharField(max_length=100)
    description = models.TextField()
    #image = models.ImageField(default='placeholder.jpg', upload_to='jobworkstation_pics')
    phone_number = models.CharField(max_length=35, blank=True, null=True)
    job_country = models.CharField(max_length=300, blank=True, null=True)
    job_adress = models.CharField(max_length=300, blank=True, null=True)
    job_zipcode = models.CharField(max_length=300, blank=True, null=True)

    CASH = 'cash_1'
    CLICK = 'click_2'
    PAYME = 'payme_3'
    OSON = 'oson_4'
    VISA = 'visa_5'
    CRYPTOCURRENCY = 'cryptocurrency_6'
    EWALLET = 'ewallet_7'
    CHOICES_PAYMET = (
        (CASH, 'cash'),
        (CLICK, 'click'),
        (PAYME, 'payme'),
        (OSON, 'oson'),
        (VISA, 'visa'),
        (CRYPTOCURRENCY, 'cryptocurrency'),
        (EWALLET, 'ewallet'),
    )
    payment_type = models.CharField(max_length=20, choices=CHOICES_PAYMET, default=CASH)
    FIXED = 'fixed_1'
    HOURLY = 'hourly_1'
    BY_PROJECT = 'by_project_1'
    CHOICES_SALARY = (
        (FIXED, 'fixed'),
        (HOURLY, 'hourly'),
        (BY_PROJECT, 'by_project'),
    )
    salary_type = models.CharField(max_length=100, choices=CHOICES_SALARY, default=FIXED)

    wage_min = models.CharField(max_length=100)
    wage_max = models.CharField(max_length=100)

    UZS = 'uzs_1'
    USD = 'usd_2'
    EUR = 'eur_3'
    RUBL = 'rubl_4'
    CHOICES_CURRENCY = (
        (UZS, 'uzs'),
        (USD, 'usd'),
        (EUR, 'eur'),
        (RUBL, 'rubl'),
    )
    currency = models.CharField(max_length=100, choices=CHOICES_CURRENCY, default=UZS)

    ONLINE = 'online_1'
    OFFLINE = 'offline_2'
    CHOICES_EMPLOYEE = (
        (ONLINE, 'online'),
        (OFFLINE, 'offline'),
    )
    employee_type = models.CharField(max_length=100, choices=CHOICES_EMPLOYEE, default=OFFLINE)


    MALE = 'male_1'
    FEMALE = 'female_2'
    ANY = 'any_3'
    CHOICES_GENDER = (
        (MALE, 'male'),
        (FEMALE, 'female'),
        (ANY, 'any'),
    )
    preffered_gender = models.CharField(max_length=100, choices=CHOICES_GENDER, default=MALE)

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived'),
    )


    created_by = models.ForeignKey(User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self):
        return self.title
    
class Application(models.Model):
    job = models.ForeignKey(Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    




# Create your models here.

apps/job/forms.py
from django import forms

from .models import Job, Application


class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'description', 'phone_number', 
        'job_country', 'job_adress', 
        'job_zipcode', 'payment_type', 
        'salary_type', 'wage_min', 
        'wage_max', 'currency', 
        'employee_type', 'preffered_gender']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['content', 'experience']

    

apps/job/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Job
from apps.notification.utilities import create_notification
from .forms import AddJobForm, ApplicationForm


from django.http import JsonResponse
import stripe
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import razorpay

def search(request):
    return render(request, 'job/search.html')
    
def job_detail(request, job_id, **kwargs):
    job = Job.objects.get(pk=job_id)   

    if request.method == 'POST':
        amount = 50000
        client = razorpay.Client(
            auth=('rzp_test_ExeUGieMdyvqvk', 'caoGVPn9zvnCVFY72aqCnv1e'))
        payment = client.order.create({'amount': amount, 'currency': 'INR', 'payment_capture': '1'})

    # OPTIONALclient.order.create(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes)
    return render(request, 'job/job_detail.html', {'job': job})


@csrf_exempt       
def success(request):
    return render(request, 'job/success.html')


@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)

        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = request.user
            application.save()

            create_notification(request, job.created_by, 'application', extra_id=application.id)

            return redirect('dashboard')
    else:
        form = ApplicationForm()
    
    return render(request, 'job/apply_for_job.html', {'form': form, 'job': job})





@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobForm(request.POST)

        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()


            return redirect('dashboard')
    else:
        form = AddJobForm()
    
    return render(request, 'job/add_job.html', {'form': form})


@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)

    if request.method == 'POST':
        form = AddJobForm(request.POST, instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm(instance=job)
    
    return render(request, 'job/edit_job.html', {'form': form, 'job': job})

apps/job/templates/job/add_job.html
{% extends 'core/base.html' %} {% block content %}
<div id="add-job-app">
    <h1 class="title">Add job</h1>

    <form v-on:submit="validateForm" method="post" action=".">
        {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
        <div class="notification is-danger">
            {{ error }}
        </div>
        {% endfor %} {% endif %}

        <div class="notification is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label>Title</label>

            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label>Description</label>

            <div class="control">
                <textarea class="textarea" name="description" id="id_description" v-model="description"></textarea>
            </div>
        </div>

        <div class="field">
            <label>Phone Number of Employer</label>

            <div class="control">
                <input class="input" name="phone_number" id="id_phone_number"></input>
            </div>
        </div>

        <div class="field">
            <label>Job Country</label>

            <div class="control">
                <input class="input" type="text" name="job_country" id="id_job_country" v-model="job_country">
            </div>
        </div>

        <div class="field">
            <label>Job address</label>

            <div class="control">
                <input class="input" type="text" name="job_adress" id="id_job_adress">
            </div>
        </div>

        <div class="field">
            <label>Zipcode</label>

            <div class="control">
                <input class="input" type="text" name="job_zipcode" id="id_job_zipcode">
            </div>
        </div>

        <div class="field">
            <label>Payment Type</label>
            <div class="control">
                <div class="select">
                    <select name="payment_type" v-model="payment_type">
                            <option value="">Choose Type</option>
                            <option value="cash_1">CASH</option>
                            <option value="click_2">CLICK</option>
                            <option value="payme_3">PAYME</option>
                            <option value="oson_4">OSON</option>
                            <option value="visa_5">VISA</option>
                            <option value="cryptocurrency_6">CRYPTOCURRENCY</option>
                            <option value="ewallet_7">EWALLET</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Salary Type</label>

            <div class="control">
                <div class="select">
                    <select name="salary_type" v-model="salary_type">
                            <option value="">Choose Type</option>
                            <option value="fixed_1">FIXED</option>
                            <option value="hourly_1">HOURLY</option>
                            <option value="by_project_1">BY_PROJECT</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Min-Wage</label>

            <div class="control">
                <input class="input" type="text" name="wage_min" id="id_wage_min" v-model="wage_min">
            </div>
        </div>
        <div class="field">
            <label>Max-Wage</label>

            <div class="control">
                <input class="input" type="text" name="wage_max" id="id_wage_max" v-model="wage_max">
            </div>
        </div>

        <div class="field">
            <label>Currency</label>

            <div class="control">
                <div class="select">
                    <select name="currency" v-model="currency">
                            <option value="">Choose Currency</option>
                            <option value="uzs_1">UZS</option>
                            <option value="usd_2">USD</option>
                            <option value="eur_3">EUR</option>
                            <option value="rubl_4">RUBL</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Employee Type</label>

            <div class="control">
                <div class="select">
                    <select name="employee_type" v-model="employee_type">
                            <option value="">Choose Employee Type Here</option>
                            <option value="online_1">ONLINE</option>
                            <option value="offline_2">OFFLINE</option>

                        </select>
                </div>
            </div>
        </div>

        <label>Preffered Gender for The Job</label>

        <div class="control">
            <div class="select">
                <select name="preffered_gender" v-model="preffered_gender">
                            <option value="">Select Gender</option>
                            <option value="male_1">MALE</option>
                            <option value="female_2">FEMALE</option>
                            <option value="any_3">ANY</option>

                </select>
            </div>
        </div>




        <div class="field">
            <div class="control">
                <button class="button is-success" type="submit">Submit</button>
            </div>
        </div>
    </form>
</div>
{% endblock %} {% block scripts %}
<script>
    const AddJobApp = {
        data() {
            return {
                title: '',
                description: '',
                job_country: '',
                payment_type: '',
                salary_type: '',
                wage_min: '',
                wage_max: '',
                currency: '',
                employee_type: '',
                preffered_gender: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.job_country === '') {
                    this.errors.push('The Country of job field is missing!')
                }

                if (this.payment_type === '') {
                    this.errors.push('The payment type is missing!')
                }
                if (this.salary_type === '') {
                    this.errors.push('The salary type is missing!')
                }
                if (this.wage_min === '') {
                    this.errors.push('The minimum wage field is missing!')
                }
                if (this.wage_max === '') {
                    this.errors.push('The maximum wage field is missing!')
                }
                if (this.currency === '') {
                    this.errors.push('The currency type is missing!')
                }
                if (this.employee_type === '') {
                    this.errors.push('The employee type is missing!')
                }
                if (this.preffered_gender === '') {
                    this.errors.push('The gender type is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(AddJobApp).mount('#add-job-app');
</script>
{% endblock %}

apps/job/templates/job/apply_for_job.html
{% extends 'core/base.html' %} {% block content %}

<h1 class="title">Thank you for purchasing the job, you can approach to the employer by filling this forms and messenging directly to the employer</h1>

<hr>
<h1 class="title">Apply for job - {{ job.title }}</h1>
<hr>
<p class="is-size-4">{{ job.description }}</p>
<hr>
<h1 class="subtitle">Here is More Detailed Information On Job: </h1>
<b>Employer phone number: </b>{{ job.phone_number}}<br>
<b>Location: </b>{{ job.job_country}}, {{ job.job_adress }}, {{ job.job_zipcode }}<br>
<b>Payment Type: </b>{{ job.get_payment_type_display}}<br>
<b>Salary Type: </b>{{ job.get_salary_type_display}}<br>
<b>Wage: </b>{{ job.wage_min}}-{{ job.wage_max }} in {{ job.get_currency_display }}<br>
<b>Employee Type: </b>{{ job.get_employee_type_display}}<br>
<b>Employee gender: </b>{{ job.get_preffered_gender_display}}<br>

<form action="" method="POST">
    {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
    <div class="notification is-danger">
        {{ error }}
    </div>
    {% endfor %} {% endif %}




    <div class="field">
        <label for="">Content</label>
        <div class="control">
            <textarea class="textarea" name="content" id="id_content"></textarea>

        </div>
    </div>

    <div class="field">
        <label for="">Experience</label>
        <div class="control">
            <textarea class="textarea" name="experience" id="id_experience"></textarea>

        </div>
    </div>

    <div class="field">
        <div class="control">
            <button class="button is-success">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

apps/job/templates/job/edit_job.html
{% extends 'core/base.html' %} {% block content %}
<div id="edit-job-app">
    <h1 class="title">Edit job</h1>

    <form v-on:submit="validateForm" method="post" action=".">
        {% csrf_token %} {% if form.errors %} {% for error in form.errors %}
        <div class="notification is-danger">
            {{ error }}
        </div>
        {% endfor %} {% endif %}

        <div class="notification is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <div class="field">
            <label>Title</label>

            <div class="control">
                <input class="input" type="text" name="title" id="id_title" v-model="title">
            </div>
        </div>

        <div class="field">
            <label>Description</label>

            <div class="control">
                <textarea class="textarea" name="description" id="id_description" v-model="description"></textarea>
            </div>
        </div>

        <div class="field">
            <label>Phone Number of Employer</label>

            <div class="control">
                <input class="input" name="phone_number" id="id_phone_number" value="{% if job.phone_number %}{{ job.phone_number }}{% endif %}"></input>
            </div>
        </div>

        <div class="field">
            <label>Job Country</label>

            <div class="control">
                <input class="input" type="text" name="job_country" id="id_job_country" v-model="job_country">
            </div>
        </div>

        <div class="field">
            <label>Job address</label>

            <div class="control">
                <input class="input" type="text" name="job_adress" id="id_job_adress" value="{% if job.job_adress %}{{ job.job_adress }}{% endif %}">
            </div>
        </div>

        <div class="field">
            <label>Zipcode</label>

            <div class="control">
                <input class="input" type="text" name="job_zipcode" id="id_job_zipcode" value="{% if job.job_zipcode %}{{ job.job_zipcode }}{% endif %}">
            </div>
        </div>

        <div class="field">
            <label>Payment Type</label>
            <div class="control">
                <div class="select">
                    <select name="payment_type" v-model="payment_type">
                            <option value="">Choose Type</option>
                            <option value="cash_1">CASH</option>
                            <option value="click_2">CLICK</option>
                            <option value="payme_3">PAYME</option>
                            <option value="oson_4">OSON</option>
                            <option value="visa_5">VISA</option>
                            <option value="cryptocurrency_6">CRYPTOCURRENCY</option>
                            <option value="ewallet_7">EWALLET</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Salary Type</label>

            <div class="control">
                <div class="select">
                    <select name="salary_type" v-model="salary_type">
                            <option value="">Choose Type</option>
                            <option value="fixed_1">FIXED</option>
                            <option value="hourly_1">HOURLY</option>
                            <option value="by_project_1">BY_PROJECT</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Min-Wage</label>

            <div class="control">
                <input class="input" type="text" name="wage_min" id="id_wage_min" v-model="wage_min">
            </div>
        </div>
        <div class="field">
            <label>Max-Wage</label>

            <div class="control">
                <input class="input" type="text" name="wage_max" id="id_wage_max" v-model="wage_max">
            </div>
        </div>

        <div class="field">
            <label>Currency</label>

            <div class="control">
                <div class="select">
                    <select name="currency" v-model="currency">
                            <option value="">Choose Currency</option>
                            <option value="uzs_1">UZS</option>
                            <option value="usd_2">USD</option>
                            <option value="eur_3">EUR</option>
                            <option value="rubl_4">RUBL</option>
                        </select>
                </div>
            </div>
        </div>

        <div class="field">
            <label>Employee Type</label>

            <div class="control">
                <div class="select">
                    <select name="employee_type" v-model="employee_type">
                            <option value="">Choose Employee Type Here</option>
                            <option value="online_1">ONLINE</option>
                            <option value="offline_2">OFFLINE</option>

                        </select>
                </div>
            </div>
        </div>

        <label>Preffered Gender for The Job</label>

        <div class="control">
            <div class="select">
                <select name="preffered_gender" v-model="preffered_gender">
                            <option value="">Select Gender</option>
                            <option value="male_1">MALE</option>
                            <option value="female_2">FEMALE</option>
                            <option value="any_3">ANY</option>

                </select>
            </div>
        </div>


        <label>Job Status</label>

        <div class="control">
            <div class="select">
                <select name="status">
                            <option value="active" {% if job.status == 'active' %} selected{% endif %}>Active</option>
                            <option value="employed" {% if job.status == 'employed' %} selected{% endif %}>Employed</option>
                            <option value="archived" {% if job.status == 'archived' %} selected{% endif %}>Archived</option>

                </select>
            </div>
        </div>

        




        <div class="field">
            <div class="control">
                <button class="button is-success" type="submit">Update</button>
            </div>
        </div>
    </form>
</div>
{% endblock %} {% block scripts %}
<script>
    const EditJobApp = {
        data() {
            return {
                title: '{{ job.title }}',
                description: '{{ job.description }}',
                job_country: '{{ job.job_country }}',
                payment_type: '{{ job.payment_type }}',
                salary_type: '{{ job.salary_type }}',
                wage_min: '{{ job.wage_min }}',
                wage_max: '{{ job.wage_max }}',
                currency: '{{ job.currency }}',
                employee_type: '{{ job.employee_type }}',
                preffered_gender: '{{ job.preffered_gender }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.job_country === '') {
                    this.errors.push('The Country of job field is missing!')
                }

                if (this.payment_type === '') {
                    this.errors.push('The payment type is missing!')
                }
                if (this.salary_type === '') {
                    this.errors.push('The salary type is missing!')
                }
                if (this.wage_min === '') {
                    this.errors.push('The minimum wage field is missing!')
                }
                if (this.wage_max === '') {
                    this.errors.push('The maximum wage field is missing!')
                }
                if (this.currency === '') {
                    this.errors.push('The currency type is missing!')
                }
                if (this.employee_type === '') {
                    this.errors.push('The employee type is missing!')
                }
                if (this.preffered_gender === '') {
                    this.errors.push('The gender type is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditJobApp).mount('#edit-job-app');
</script>
{% endblock %}

apps/job/templates/job/job_detail.html
{% extends 'core/base.html' %} {% block content %}
<h1 class="title">{{ job.title }} ({{ job.get_status_display }}) </h1>

<p class="is-size-4">{{ job.description }}</p>

<b>Location: </b>{{ job.job_country}}<br>
<b>Payment Type: </b>{{ job.get_payment_type_display}}<br>
<b>Salary Type: </b>{{ job.get_salary_type_display}}<br>
<b>Wage: </b>{{ job.wage_min}}-{{ job.wage_max }} in {{ job.get_currency_display }}<br>
<b>Employee Type: </b>{{ job.get_employee_type_display}}<br>
<b>Employee gender: </b>{{ job.get_preffered_gender_display}}<br>



<hr> {% if job.status == 'active' %}
<form class="text-center border border-light p-5" action="{% url 'apply_for_job' job.id %}" method="POST">
    {% csrf_token %}
    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_ExeUGieMdyvqvk" data-amount="50000" data-currency="INR" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay" data-name="{{job.title}}" data-description="charge for job purchase"
        data-image="https://example.com/your_logo.jpg" data-prefill.name="111" data-prefill.email="{{user.email}}" data-theme.color="#F37254"></script>
</form>
{% else %}
<p>This job is not available anymore!</p>
{% endif %} {% endblock %}

apps/job/templates/job/search.html
{% extends 'core/base.html' %} {% block content %}
<div id="search-app">
    <h1 class="title">Search</h1>

    <form @submit.prevent="performSearch()">
        <div class="columns">
            <div class="column is-4">
                <div class="field">
                    <label>Search by Job Title</label>

                    <div class="control">
                        <input type="text" name="query" class="input" v-model="query">
                    </div>
                </div>

                <div class="field">
                    <label>Employee Type</label>

                    <div class="control">
                        <div class="select">
                            <select name="employee_type" v-model="employee_type">
                            <option value="">All</option>
                            <option value="online_1">ONLINE</option>
                            <option value="offline_2">OFFLINE</option>

                        </select>
                        </div>
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div v-if="jobs.length">
        <hr>

        <div v-for="job in jobs" :key="job.id" class="notification mt-2">
            <h3 class="is-size-4">[[ job.title ]]</h3>
            <p>[[ job.description ]] </p>
            <p>[[ job.wage_min ]] - [[ job.wage_max ]] [[ job.currency ]]</p>

            <a :href="job.url" class='button is-success'>View details</a>
        </div>
    </div>
</div>
{% endblock %} {% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '',
                wage_min: '',
                wage_max: '',
                employee_type: '',
                jobs: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query,
                    'employee_type': this.employee_type
                }

                fetch('/jobs/api/search/', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify(data)
                    })
                    .then((response) => {
                        return response.json()
                    })
                    .then((result) => {

                        this.jobs = result.jobs
                    })
                    .catch((error) => {
                        console.log('Error', error)
                    })
            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>

{% endblock %}

apps/job/templates/job/success.html
{% extends 'core/base.html' %} {% block title %} Thank You {% endblock %} {% block content %}
<div class="container">
    <h1 class="title">Thank you</h1>
</div>

{% endblock %}